Controllers/CheckTableController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TestWork.Data;
using TestWork.Models;

namespace TestWork.Controllers
{
    public class CheckTableController : Controller
    {
        private readonly ILogger<CheckTableController> _logger;
        private readonly DataContext _context;

        public CheckTableController(ILogger<CheckTableController> logger, DataContext context)
        {
            _context = context;
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index(CardModelView obj)
        {
            List<CardModelDataView> results = _context.Cards.Select(c => new CardModelDataView
            {
                CardCode = c.CardCode,
                StartDate = c.StartDate,
                FinishDate = c.FinishDate,
                LastName = c.LastName,
                FirstName = c.FirstName,
                SurName = c.SurName,
                FullName = c.FullName,
                GenderId = c.GenderId,
                Birthday = c.Birthday,
                PhoneHome = c.PhoneHome,
                PhoneMobil = c.PhoneMobil,
                Email = c.Email,
                City = c.City,
                Street = c.Street,
                House = c.House,
                Apartment = c.Apartment,
                AltAddress = c.AltAddress,
                CardType = c.CardType,
                OwnerGUID = c.OwnerGUID,
                CardPer = c.CardPer,
                TurnOver = c.TurnOver
            }).ToList();
            
            obj.Data = results;

            return View(obj);
        }

        public IActionResult ChangeData(CardModelDataView obj) 
        {
            return View(obj);
        }

        [HttpPost]
        public IActionResult SaveData(CardModelDataView obj, string firstName, 
        string lastName, string surname, DateTime birthday) 
        {
            var value = _context.Cards.Where(c => c.CardCode == obj.CardCode).First();
            
            value.FirstName = firstName;
            value.LastName = lastName;
            value.SurName = surname;
            value.Birthday = birthday;

            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult CheckCardData(CardModelDataView obj) 
        {
            return View(obj);
        }

        [HttpPost]
        public IActionResult CheckPersonalData(CardModelDataView obj) 
        {
            return View(obj);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/LoadFileController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using TestWork.Data;
using TestWork.Models;
using System.Xml;

namespace TestWork.Controllers
{
    public class LoadFileController : Controller
    {
        private readonly ILogger<LoadFileController> _logger;
        private readonly DataContext _context;

        public LoadFileController(ILogger<LoadFileController> logger, DataContext context)
        {
            _context = context;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult UploadXml(CardModelView model)
        {
            if (model.XmlFile != null && model.XmlFile.Length > 0)
            {
                using (var reader = new StreamReader(model.XmlFile.OpenReadStream()))
                {
                    var xmlContent = reader.ReadToEnd();

                    XmlDocument xmlDoc = new();
                    xmlDoc.LoadXml(xmlContent);

                    XmlNodeList cardNodes = xmlDoc.SelectNodes("//Card");

                    foreach (XmlNode cardNode in cardNodes)
                    {
                        CardModel card = new();
                        XmlAttribute cardCodeAttribute = cardNode.Attributes["CARDCODE"]!;

                        card.CardCode = Int64.Parse(cardNode.Attributes["CARDCODE"].Value);
                        card.StartDate = string.IsNullOrEmpty(cardNode.Attributes["STARTDATE"].Value) ?
                            (DateTime?)null : DateTime.Parse(cardNode.Attributes["STARTDATE"].Value);
                        card.FinishDate = string.IsNullOrEmpty(cardNode.Attributes["FINISHDATE"].Value) ?
                            (DateTime?)null : DateTime.Parse(cardNode.Attributes["FINISHDATE"].Value);
                        card.LastName = cardNode.Attributes["LASTNAME"].Value;
                        card.FirstName = cardNode.Attributes["FIRSTNAME"].Value;
                        card.SurName = cardNode.Attributes["SURNAME"].Value;
                        card.FullName = cardNode.Attributes["FULLNAME"].Value;
                        card.GenderId = int.Parse(cardNode.Attributes["GENDERID"].Value);
                        card.Birthday = string.IsNullOrEmpty(cardNode.Attributes["BIRTHDAY"].Value) ?
                            (DateTime?)null : DateTime.Parse(cardNode.Attributes["BIRTHDAY"].Value);
                        card.PhoneHome = cardNode.Attributes["PHONEHOME"].Value;
                        card.PhoneMobil = cardNode.Attributes["PHONEHOME"].Value;
                        card.Email = cardNode.Attributes["EMAIL"].Value;
                        card.City = cardNode.Attributes["CITY"].Value;
                        card.Street = cardNode.Attributes["STREET"].Value;
                        card.House = cardNode.Attributes["HOUSE"].Value;
                        card.Apartment = cardNode.Attributes["APARTMENT"].Value;
                        card.AltAddress = cardNode.Attributes["ALTADDRESS"].Value;
                        card.CardType = cardNode.Attributes["CARDTYPE"].Value;
                        card.OwnerGUID = cardNode.Attributes["OWNERGUID"].Value;
                        card.CardPer = int.Parse(cardNode.Attributes["CARDPER"].Value);
                        card.TurnOver = double.Parse((cardNode.Attributes["TURNOVER"].Value).Replace(".", ","));

                        _context.Cards.Add(card);
                        

                    }

                    _context.SaveChanges();
                }

                ViewBag.Message = "Данные успешно добавлены в базу данных.";
            }

            return View("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TestWork</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TestWork.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="CheckTable" asp-action="Index">TestWork</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LoadFile" asp-action="Index">Загрузить файл XML</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CheckTable" asp-action="Index">Содержимое таблицы</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TestWork - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>